### ISSUE TITLE
Cannot create_tables() multiple times

### ISSUE THREAD

**Issue by hrharkins** [linkyndy/remodel#13]
Running create_tables() on an existing database produces an "already exists" error.  Somewhat understandable but as a schema develops it is bound to add new tables/models as time goes on.  It seems to me that create_tables() should have an option to avoid creating already existing tables or at catching  that error and carrying on.

Alternatively having a clear public interface for the application to do that work itself (exposing/documenting registry) would seem reasonable.

I haven't gotten that far, but I'm betting the same might be said for create_indexes...

**Comment by linkyndy** [comment]
Indeed, this issue is on my short list for the upcoming v0.4.0 release. Will address it as soon as I have time because I stumbled upon this issue several times myself. `create_indexes` has the same issue.

I don't want to expose the registry, it should be used only in "emergency" cases. Rather, I will work on these so-called helpers, leveraging operations that involve the registry (such as `create_tables`, `create_indexes`).

I'll try to roll these updates in the near future, stay tuned and thanks for spotting the issue :+1:
