### ISSUE TITLE
Default fields and values

### ISSUE THREAD

**Issue by hegga** [linkyndy/remodel#15]
Hi!

Great module! I'm not sure if this is a support request or a feature request, but how
can I add default fields and values to my models? For example:

class User(Model): 
    is_active = True
    created_date = datetime.datetime.utcnow()

**Comment by linkyndy** [comment]
remodel is built on the concepts of RethinkDB and NoSQLs in general: there is no schema, hence models do not expect certain fields to be passed or set by default. However, if you really need to enforce default values (so that you always save a field even though it wasn't set on the object) you can do it by overriding the `save()` method on your custom model class, so you can end up with something like:

```python
class User(Model):
    def save(self):
        self['is_active'] = True
        super(User, self).save()
```

Callbacks are currently in works for the next release of remodel which will allow you to define a custom method that will be called before save (for example); you would place your default value assignments there. More on this after the next release.

remodel is designed to be as simple as possible and hopefully the implementation of callbacks will do the trick for you without "loading" models with field definitions.

**Comment by linkyndy** [comment]
remodel v0.4.0 is out now, with callback support. Head over to the [wiki](https://github.com/linkyndy/remodel/wiki/Callbacks) page for more details.

@hegga, you could use callbacks for what you're trying to achieve:

```python
class User(Model):
    def after_init(self):
        self['is_active'] = True
        self['created_date'] = datetime.datetime.utcnow()
```

Closing this, but feel free to reopen the issue for any other question related to this.
