### ISSUE TITLE
Add durability to delete

### ISSUE THREAD

**Issue by scripter-co** [linkyndy/remodel#22]
When running

```
model.delete()
```

you should be able to provide durability, which is present in the python rethinkdb driver:

```
table.delete([durability="hard", return_changes=False]) → object
selection.delete([durability="hard", return_changes=False]) → object
singleSelection.delete([durability="hard", return_changes=False]) → object
```

(durability: possible values are `hard` and `soft`)

and when fetching results:

   model.get_all()

anything with a `soft` delete is not included (and the same with any joined results)

**Comment by linkyndy** [comment]
Adding durability only to delete won't keep the interface transparent, since durability may be provided to several other operations as well.

One idea may be to provide an option for a model which will set the durability for the whole table. But then people may want to run part of their queries using a different durability.

Finally, since associations are at stake, how can you make sure that an associated record, soft written, can be safely used in operations on the parent model without losing data or corrupting the parent link? You could use `sync`, but that would make queries harder to implement.

Is there any specific use case for your proposal? Because if it is only a side wish, you could always build the query yourself and use whatever durability you wish (`User.get(...).delete(durability='soft').run()`).

**Comment by scripter-co** [comment]
Sorry. You can ignore this issue, please delete it.

**Comment by linkyndy** [comment]
No, don't be sorry. I appreciate any feedback and I'm trying to implement whatever you guys find necessary. For the above I was questioning whether it's worth it since you can, for exceptional cases, use the normal ReQL syntax directly on the model.

If this is really needed, I believe putting a table option would be the cleanest solution, although it doesn't solve all possible cases.

Will keep this open and will mark as a discussion, maybe there are others that need durability too.

**Comment by linkyndy** [comment]
Closing this one since it didn't get more comments. But feel free to reopen if there's something more to add!
