### ISSUE TITLE
Wrapping function calls __setattr_ validations

### ISSUE THREAD

**Issue by derkan** [linkyndy/remodel#24]
Hi,
Correct me if I'm wrong, in ObjectHandler._wrap method:
```py
    def _wrap(self, doc):
        obj = self.model_cls()
        # Assign fields this way to skip validation
        obj.fields.__dict__ = doc
        return obj
```
Code for description `Assign fields this way to skip validation` doesn't do what it says. `fields.__setattr__` is called anyway.

My proposal is to change code with this:
```py
    def _wrap(self, doc):
        obj = self.model_cls()
        # Assign fields this way to skip validation
        obj.fields.__dict__.update(doc)
        return obj
```
By this way fetching data into model object is 1,8x faster.

Regards

**Comment by linkyndy** [comment]
Firstly, thanks for digging in how remodel is implemented!

Indeed, `setattr` is called, with `__dict__` as the attribute that is set. That's why it kind of "skips" validation. It still enters validation, but not for the current field though. Just as general information, there are tests covering this, and assigning fields **with** validation in this case would've made the suite fail (the same approach is used in several places throughout the code base).

Getting back, using `__dict__.update` would really skip that validation, but I see one problem with it: we currently hard reset the object's fields, in case some old values are still there. By updating the dict, those old traces may still be there, making their detection very tricky. This may not work in all cases where we skip validation, but can legitimately apply in this one. For instance, we have the same assignment in `Model.save` where I don't think it's good to swap it for an `update`.

In the end, I think your proposal is viable for this single occurance. You are more than welcome to open a pull request (on the _develop_ branch) for this change, maybe enhancing the existing inline comment to reflect the reason for the change (it'll help for future reference). If you wish not to do this, I will make the changes in a couple of days.

Thanks for your help!

**Comment by derkan** [comment]
Thanks for detailed answer. I am issuing a pull request.

**Comment by linkyndy** [comment]
Merged the your pull request, thank you very much for your [contribution](https://github.com/linkyndy/remodel/blob/develop/AUTHORS.md)!
