### ISSUE TITLE
Connection pool does not honor changing db

### ISSUE THREAD

**Issue by kamilion** [linkyndy/remodel#27]
I've been trying to port my flask superframework stuff over to using remodel, and I've run into some problems.

First off, was just trying to figure out how to specify an auth_key.

Thankfully there was some 'old' documentation on the rethinkdb blog:
http://www.rethinkdb.com/blog/remodel/

It was the only place I found remodel.connection.pool.configure() documented.

Anyway, I'm using flask-classy, and each of my 'plugins' do their own imports.
However, everything wants the User object to be around for flask-login's methods to be happy.
https://github.com/kamilion/kaizen/blob/master/auth/authmodel.py#L23

I previously had each module in a different database, but in moving to remodel, I found I could only reliably talk to a single db, versus my previous bare reql.

https://github.com/kamilion/mcubed-web/blob/master/auth/authmodel.py#L95

Here's the change in configurations:
https://github.com/kamilion/kaizen/blob/master/app/config.py.example#L45
versus:
https://github.com/kamilion/mcubed-web/blob/master/app/config.py.example#L44

I'm trying to figure out what the best way to solve this problem is.

So far, my leaning is towards a deeper level change versus trying to bandaid the connection pool.

I could (in order of complexity of code):
  alter the connection pool to be aware of each connection's db (ick, but my code doesn't change)
  alter the Model to allow a 'default' db if not overridden, move r.db() from connection.pool -> Model
  flush/empty the connection pool when a configuration change occurs (ick, sledgehammer)
  alter the connection pool to provide a pool of connections for each db (ick, violates DRY)

Thoughts, feelings, flames, comments?

**Comment by linkyndy** [comment]
First of all, appreciate your interest in remodel!

I agree that the docs are not as good as I wished, that's why #4 is still open :) . Yes, that's the way to configure remodel's connection, I reckon I've mentioned it somewhere but now it seems to be gone. I'll further work on the docs this summer.

Remodel was developed as a very simple and easy ODM, so I didn't find the need at that point to be able to talk to multiple databases. As a matter of fact, is there any specific reason to store every different entity in a separate database?

Regarding your proposals, here are my thoughts on them:

- how would you initialize the pool this way and how would you select connections based on the database you need? A major refactor would be necessary for the connection pool in order to do this;
- could work, but then the connection pool will be strongly coupled to the model class. I don't find this very encouraging;
- it would definitely impact the performance, especially if you have multiple databases you need;
- indeed, this would add a big overhead for all those connections.

In the end, I'm open to any suggestions (see #26 also, regarding a potential refactor on the connection pool). I haven't spent too much time on the connection pool since it does it's job as it's currently implemented. I don't have a simple answer to your question, but I'll think about it the next week when I'll have more time. I'll gladly implement any change you propose, as long as it doesn't deviate too much from remodel's main principle of being simple and easy.

**Comment by kamilion** [comment]
Actually, I was only using two databases beforehand, 'kaizen' and 'kaizen_auth', as several applications can/may share the auth db. However, I was intending on building additional applications/plugins that may wish to speak to other databases on the cluster.

More specifically, as an example, I have a tool that converts smartmontools' smartctl output into json and a python wrapper around that to stuff the json into rethinkdb as a document update to a specific drive by looking it up by: WWN, serial number, or bus path if both WWN/SN are unavailable.
That tool should probably be pushing data into it's own database and tables, where any/all frontends can later either aggrigate the documents or watch for .changes().

I'll fork and attempt the second choice, and submit a PR for it to be judged.

I know you're trying to be minimal and transparent; I was trying to be minimal too with ReOBJ, but in practice it's harder to fight simplicity than adequate complexity + comments. Triplequotes are your friend. :) 

You're much farther along than I got, and I got over my annoyance of having to call .save() on single records, so now I've stopped bothering with trying to fight with making ReOBJ work and I'll just fix the two or three skinned knees that bugged me about remodel instead of trying to be ultra minimal.

BTW, my old pooling worked just fine without specifying the db up front.
https://github.com/kamilion/mcubed-web/blob/master/reobj/reobj.py#L55


Currently, I'm thinking the following: the DB configured with remodel.connection.pool.configure() simply becomes the implicit default used by all models unless specifically overridden in a subclassed model.

Then all I have to do is tell my auth model it should use the override to choose a different database (kaizen_auth); while everyone and everything else should be perfectly happy running the same old code unmodified.

Sound good?

**Comment by linkyndy** [comment]
One thing that it's for sure, there certainly are use cases of remodel that don't cover someone's needs. Therefore, remodel being simple and extensible, you can always extend it until it covers all your desired needs. Just be aware that if you introduce major changes you probably won't be able to support future versions of remodel. If the changes you implement add a real value and may be useful to others, I will gladly make it available to everyone in a future release.

So, you should do whatever you like with remodel to fit your project, and maybe we'll be able to merge it into the original project.

**Comment by linkyndy** [comment]
Closing this for now, but feel free to reopen if you want to add something!
