### ISSUE TITLE
Documents with lists may not be able to save on update

### ISSUE THREAD

**Issue by cjhenck** [linkyndy/remodel#29]
If a document has fields with lists, save may complain about being non-deterministic.  I've made some changes to the field manager that would keep track of dirty fields and then only update those, which should have the same effect but be atomic.  I'll make a pull request as soon as it's well tested.

**Comment by linkyndy** [comment]
From my knowledge, lists should work fine with remodel. Can you post an example about the issue you've encountered?

Also, I wanted to add dirty fields, but I felt it added too much overhead to the operations, making remodel slower. Since they didn't add that much value to remodel, I've decided not to implement them at that time.

**Comment by cjhenck** [comment]
I finally was able to investigate this fully.  Seems it's a geojson problem, not lists.

https://github.com/rethinkdb/rethinkdb/issues/3864
