### ISSUE TITLE
"current instance isn't saved"-error

### ISSUE THREAD

**Issue by sjovang** [linkyndy/remodel#31]
Here's the code-example. Simple enough stuff

    def create_default_roles(
            roles = ['Administrator', 'Service Desk', 'Customer']):
        for role in roles:
            r = Role.get(name=role)
            if r is None:
                Role.create(name=role)

    def create_default_user(username='admin',
                            name='Administrator',
                            email=current_app.config['ADMIN_EMAIL'],
                            password='admin',
                            role='Administrator'):
        aes = SimpleAES(current_app.config['SECRET_KEY'])
        if User.get(username=username) is None:
            User.create(name=name,
                        username=username,
                        email=email,
                        password=aes.encrypt(password),
                        role=Role.get(name=role))

    remodel.connection.pool.configure(db=current_app.config['RDB_DB'])
    remodel.utils.create_tables()
    remodel.utils.create_indexes()

    create_default_roles()
    create_default_user()

And here's the error-message with relevant stack-trace
> File "manage.py", line 35, in create_default_user
>    role=Role.get(name=role))
>  File "/Users/tsg/.virtualenv/cdn-api/lib/python2.7/site-packages/remodel/object_handler.py", line 16, in > create
>    obj = self.model_cls(**kwargs)
>  File "/Users/tsg/.virtualenv/cdn-api/lib/python2.7/site-packages/remodel/models.py", line 65, in __init__
>    setattr(self.fields, key, value)
>  File "/Users/tsg/.virtualenv/cdn-api/lib/python2.7/site-packages/remodel/field_handler.py", line 79, in __setattr__
>    super(FieldHandler, self).__setattr__(name, value)
>  File "/Users/tsg/.virtualenv/cdn-api/lib/python2.7/site-packages/remodel/related.py", line 52, in __set__
>    'saved' % value)
> ValueError: Cannot assign "<Role: 353202a4-086a-4091-b58a-64fbf0013d8b>": current instance isn't saved

It might just be something trivial, but I can't see what. And the documentation is not very helpful on this

**Comment by linkyndy** [comment]
What do you model definitions look like?

As a side note, there is `get_or_create` which would help you transform your 3-line snippet to a one-liner.

**Comment by drcongo** [comment]
I'm getting this as well, trying to do a similar thing. I've created a RemodelUserDatastore for Flask-Security and hit exactly the same snag. The relevant part of the datastore is this...

```
def create_user(self, **kwargs):
        """Creates and returns a new user from the given parameters."""
        kwargs = self._prepare_create_user_args(**kwargs)
        user = self.user_model.create(**kwargs)
        return self.put(user)
```

`_prepare_create_user_args` simply checks to see if it has been passed any roles names, and if so, gets the model for the role by name and returns the kwargs with a list of roles instances instead of their names.

Traceback is very similar to @sjovang's...

```
Traceback (most recent call last):
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/vagrant/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/venv/lib/python2.7/site-packages/flask_security/decorators.py", line 205, in wrapper
    return f(*args, **kwargs)
  File "/vagrant/venv/lib/python2.7/site-packages/flask_security/views.py", line 117, in register
    user = register_user(**form.to_dict())
  File "/vagrant/venv/lib/python2.7/site-packages/flask_security/registerable.py", line 29, in register_user
    user = _datastore.create_user(**kwargs)
  File "/vagrant/crackpipes/modules/rethink_security/datastore.py", line 43, in create_user
    user = self.user_model.create(**kwargs)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/object_handler.py", line 16, in create
    obj = self.model_cls(**kwargs)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/models.py", line 65, in __init__
    setattr(self.fields, key, value)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/field_handler.py", line 79, in __setattr__
    super(FieldHandler, self).__setattr__(name, value)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/related.py", line 177, in __set__
    rel_object_handler = self.__get__(instance)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/related.py", line 171, in __get__
    rel_object_handler = self.related_object_handler_cls(instance)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/related.py", line 113, in __init__
    self.query = self.query.get_all(self._get_parent_lkey(), index=rkey)
  File "/vagrant/venv/lib/python2.7/site-packages/remodel/related.py", line 152, in _get_parent_lkey
    'instance isn\'t saved' % model_cls.__name__)
ValueError: Cannot access related "Role" set: current instance isn't saved
```

The problem being, I'm still in the process of creating the instance and definitely don't want it saved yet. For the record, the kwargs getting passed to create_user look like this 

`{'password': '$2a$12$pBRz377Y3w/k9kWqQGwVAuw.Bm9Q8o8gxYWnx.q8mJ.vsFiKDQZYG', 'email': u'test@test.com'}` 

and after passing through the `_prepare_create_user_args` function (and therefore what's being piped into the `object_handler`'s `create` method) they have an added empty list for roles... 

`{'password': '$2a$12$pBRz377Y3w/k9kWqQGwVAuw.Bm9Q8o8gxYWnx.q8mJ.vsFiKDQZYG', 'email': u'test@test.com', 'roles': []}`

**Comment by drcongo** [comment]
Oh, and the model definitions! For compatibility with Flask-Security I added a bunch of fields, though I couldn't find reference on the correct way to do this in the docs...

```
class Role(Model, RoleMixin):
    has_many = ('User', )
    name = ""
    description = ""
    users = []


class User(Model, UserMixin):
    has_many = ('Role', )
    slug = ""
    email = ""
    username = ""
    password = ""
    active = False
    confirmed_at = None
    roles = []
    last_login_at = None
    current_login_at = None
    last_login_ip = ""
    current_login_ip = ""
    login_count = 0
    created_at = None
    updated_at = None
    created_by = None
    updated_by = None
    deleted = False
    roles = []
```

Is there a correct way? And as a side note, is there some way to add constraints to fields so that, for instance, I can force unique against the email field at a DB level?

Thanks

**Comment by linkyndy** [comment]
Let's discuss the issues in order. 

Firstly, remodel doesn't need a declared list of fields for its models. Since remodel works with RethinkDB, it is schemaless, allowing you to truly benefit from this. So you have no constraint (imposed by the library) on what fields to save -- just like you would do with RethinkDB. On the other side, you are free to implement a mechanism that forces you to adhere to a schema, but bare in mind that remodel does not offer this. I didn't find it within the principles of RethinkDB.

Then, you have two models, each _having many_ instances of the other model. It doesn't sound right and it would certainly not work. I believe [`has_and_belongs_to_many`](https://github.com/linkyndy/remodel#has-and-belongs-to-many) or [`has_many`-through](https://github.com/linkyndy/remodel#has-many-through) are the ones you may look for. For many-to-many relationships you need to use a third model/table.

Lastly, remodel doesn't allow you to do something like:

```python
User.create(roles=[Role(), Role()])
```

When a `User has_many Role`, the foreign key is located in the `roles` table. Therefore, when saving such a relation the `Role` instances must be saved already in the database, otherwise assigning the foreign key will fail. You can solve this by either saving `Role` instances to the database first or by using the `add()` method: 

```python
user = User()
user['roles'].add(Role())
```

I believe addressing the above points will solve your issue. If not, please come back and we will further dig into this issue.

**Comment by drcongo** [comment]
Thanks a lot. Looks like I'll have to slightly monkey patch the way that Flask-Security looks for fields on those two models. I'll keep you posted.

**Comment by linkyndy** [comment]
Good luck and come back for any help.

**Comment by linkyndy** [comment]
Closing this for the moment. Please, feel free to reopen it for any further questions you'll have about this problem.
