### ISSUE TITLE
How does the RqlQuery.run() find the settings

### ISSUE THREAD

**Issue by Gesias** [linkyndy/remodel#40]
I have gotten started with Remodel again after a bit of a hiatus. Started working on a api with the falcon framework and found that some parts of Remodel could really accommodate the coding. 

I was wondering one thing, Its somewhat of an assumption. I have a theory so maybe you could just tell me if I´m completely wrong or not. In the `remodel.Model` classes there is for example a `save()` method. That save method is calling the `RqlQuery.run()` method which if not supplied a connection will look for one in `cls.threadData` or create one with settings from environment variables?

The connection pool is never used unless used with 
`with get_conn()`
    `do stuff`

Thanks a lot for all your efforts! It´s much appreciated

**Comment by linkyndy** [comment]
Nice to have you back, @Gesias :)

`RqlQuery.run` is actually patched at remodel level, because I wanted a clean and simplistic API. You can find the actual patch in [`monkey.py`](https://github.com/linkyndy/remodel/blob/master/remodel/monkey.py#L20).

Therefore, whenever `run` is called and no connection is passed, a connection from the pool is picked and used.

If something is not clear, don't hesitate to ask!

**Comment by Gesias** [comment]
@linkyndy Thanks! 

Ah, I see it now. That was the missing piece!
