### ISSUE TITLE
Is it possible to have required model fields

### ISSUE THREAD

**Issue by SkiftCreative** [linkyndy/remodel#43]
I was wondering if there was a possibility to have a simple way to have a required set of fields on a model. One method I was thinking of was:

```
class Post(Model):
    required_fields = {
        'title',
        'author',
        'content'
    }

    def __init__(self, **kwargs):
        for field in self.required_fields:
            if field not in kwargs:
                raise KeyError('Field is required: {}'.format(field))

        super().__init__(**kwargs)
```

But will this break things or should this work? Or is there a better way to do this.

**Comment by SkiftCreative** [comment]
I did also just see this which does help, https://github.com/linkyndy/remodel/issues/15

But here, I just want to make sure they pass some value to given required field. 

It would also be interesting to try and validate those to make sure they are a needed type. But for that if I need it I could probably use something like json schema

**Comment by linkyndy** [comment]
It depends on what you are trying to achieve. If I were to check required fields, I would do this in a [`before_save` callback](https://github.com/linkyndy/remodel/wiki/Callbacks). The reasons why I didn't implement such things as fields/schemas are listed on the issue you have linked.

Since remodel is based on simplicity and modularity, you can always extend it with whatever other packages you like. There are many schema validation packages out there and you can get a hash of fields for an object with `obj.fields.as_dict()`.

**Comment by SkiftCreative** [comment]
Yea I actually prefer that a model isnt tied to a given schema. But on certain things say a blog post, i always want to make sure that there is a `title` and `content` for example. I just want to make sure some models have at least some given fields.

In regards to using the callbacks, if I want to check for those fields as early as possible wouldnt it be best to check for them in `after_init` rather than `before_save` ? Of course depending on the need. In `before_save` I could easily see validating any data I need to prior to insertion.

Also, the `obj.fields.as_dict() will be really useful as well. Thanks.

**Comment by linkyndy** [comment]
It depends on your use case. If you want to set fields right before saving, use the `before_save` callback. If you want to set fields right after initialising an object, use the `after_init` callback.

If you have these things clarified, please close this issue. Otherwise, feel free to ask me whatever is not clear.
