### ISSUE TITLE
Find substring within columns like SQLAlchemy's or_

### ISSUE THREAD

**Issue by RPiAwesomeness** [linkyndy/remodel#46]
I'm working on a project where I need to be able to search the database for a certain string in several different columns.

This was pretty simple with SQLAlchemy/SQLite (back before I started switching to RethinkDB):

```python
results = Tickets.query.filter(or_(
            Tickets.issue.contains(search_term),
            Tickets.details.contains(search_term),
            Tickets.representative.contains(search_term),
            Tickets.who.contains(search_term)
))
```

However, I can't seem to find anything like this in remodel. Is this not a feature that exists, or is it just undocumented?

There's obviously the option of doing a raw RethinkDB call:

```python
r.table('users').filter(lambda doc:
    doc['name'].match("(?i)^john$")
).run(conn)
```

but I have had no luck with that and I would prefer to do everything via remodel.

**Comment by linkyndy** [comment]
Remodel isn't very advanced and its aim isn't to provide a "native" way for all possible query combinations that RethinkDB offers. Instead, basic ODM features are provided and for the more complex ones, Remodel dispatches commands directly to RethinkDB. You can check [this section](https://github.com/linkyndy/remodel#custom-model-queries) of the README:

```ruby
import rethinkdb as r

class Celebrity(Model):
    pass

Celebrity.create(name='george clooney')
Celebrity.create(name='kate winslet')
upper = Celebrity.map({'name': r.row['name'].upcase()}).run()
print list(upper) # prints [{u'name': u'GEORGE CLOONEY'}, {u'name': u'KATE WINSLET'}]
```

As you can see, `map` is a RethinkDB function which, if called on your model, adds some syntactic sugar behind the scenes for you to perform your queries with as little boilerplate as possible. Chaining is also possible since the RethinkDB Python driver is invoked.

Hope this helped you!
