### ISSUE TITLE
ADVICE: Trying to understand relaitonships here

### ISSUE THREAD

**Issue by kiodou** [linkyndy/remodel#56]
Can i get an example what i can do with this:

```
class Artist(Model):
        has_many = (('Song', 'songs', 'id', 'song_id'), 'Concert')
        # Tuple definition: (<related model name>, <related objects accessor field>, <model key>, <related model key>)
```

Does this mean if i add multiple songs
```
a = Artist()
a.add(song_1, song_2)
```

I can access all the songs by:
`a["songs"]`
???

And also,

if **\<related objects accessor field\>** is **'id'** (id of artist?) shouldn't the **\<related model key\>** be something like **'artist_id'**?

**Comment by dlonli** [comment]
anyone?

**Comment by cemmurphy** [comment]
Hi @kiodou and @dlonli,

I believe you are correct. It should be ``artist_id`` 

With your definition of has_many in Artist, I think it should be changed to this:

```python
class Artist(Model):
        has_many = (('Song', 'songs', 'id', 'artist_id'), 'Concert')
        # Tuple definition: (<related model name>, <related objects accessor field>, <model key>, <related model key>)
```

Note that you could also leave out the Tuple definition completely and get the exact same behavior, i.e.:

```python
class Artist(Model):
        has_many = ('Song',  'Concert')
<related model key>)
```

Both "imply" the following object properties:

Artist object has an id.
Artist has a list / set of Song objects called 'songs'.
Song object has an id.
Song object has an artist_id property (reference to Artist object).

With that said, you could do something like this. **NOTE:** Not fully tested.:

```python

artist = Artist.create(name="Buddy Guy")
artist['songs'].add(Song(title="Stone Crazy"))
artist.save()

artist_id = artist['id']

# Load the artist you just created from the database with the id provided
load_artist = Artist.get(artist_id)

for song in load_artist['songs'].all():
  print(song['title']

```

Note that you're accessing the set of songs by calling ```load_artist['songs'].all()```. This is because the object return from the get contains a RelatedObjectHandler instead of the actual set of related Song objects. This is how Remodel handles lazy loading I believe.

I think a key concept here is the "state" of the object. You can't "add" dependent objects unless the parent has been "saved". Meaning the Artist has to have an id assigned before you can add / access the dependent objects.

For example, these are equivalent:

```python
artist = Artist.create(name="Buddy Guy")
artist['songs'].add(Song(title="Stone Crazy"))

artist = Artist()
artist['name'] = "Buddy Guy"
artist.save()
artist['songs'].add(Song(title="Stone Crazy"))
```

However, if you try accessing the images property without saving first you'll get an error:

```python
artist = Artist()
artist['songs'].add(...)

ValueError: Cannot access related "Song" set: current instance isn't saved
```

Hope this helps.

**Comment by dlonli** [comment]
Thanks for the help, this gave and experimenting with the code for the past week help me get a better understanding.

**Comment by linkyndy** [comment]
Sorry for getting to this issue this slow, but @cemmurphy did an excellent job with his explanations. I will close this for now, but if you have any other questions, feel free to reopen it or open another issue!
